version: '3'

services:
    app:
        build: .
        environment: 
            - DIGEST_USER=hoge
            - DIGEST_PASSWD=fuga
            - DIGEST_REALM=veryVerySecretZone
            - DIGEST_NONCE=hogefuga
        ports:
            - "18888:18888"
        volumes:
            - .:/go/src
